services:
  - type: web
    name: kotlin-backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mydb
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mydb
          property: password
      - key: PORT
        value: 8080

databases:
  - name: mydb
    databaseName: portfolio
    user: portfolio_user
    plan: free
