services:
  - type: web
    name: kotlin-backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: mydb
    databaseName: portfolio
    user: portfolio_user
    plan: free
