services:
  - type: web
    name: kotlin-backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: mydb
          property: hostExternal
      - key: DB_PORT
        fromDatabase:
          name: mydb
          property: port
      - key: DB_NAME
        fromDatabase:
          name: mydb
          property: database
      - key: DB_USER
        fromDatabase:
          name: mydb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mydb
          property: password
      - key: PORT
        value: 10000

databases:
  - name: mydb
    databaseName: portfolio
    user: portfolio_user
    plan: free
