services:
  - type: web
    name: kotlin-backend
    env: docker
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mydb
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mydb
          property: password

databases:
  - name: mydb
    databaseName: mydb
    user: myuser
    plan: free
    engine: mysql
